### ISSUE TITLE
Update Gradle configuration to use the latest version of Kotlin and Java

### ISSUE THREAD

**Issue by christianhujer** [abhiShirbhate/time-tracker#3]
Currently, the `build.gradle.kts` file contains the following entry:
`java.sourceCompatibility = JavaVersion.VERSION_1_8`

This version is old: https://www.oracle.com/technetwork/java/java-se-support-roadmap.html

We should use Java 13 or 11 (LTS).

Acceptance Criteria:
- If possible, uses the latest release version of Kotlin
- If possible, uses Java 13. Otherwise, if possible, uses Java 11.
- If latest version could not be used, go to the next latest alternative and document why the latest version could not be used.

**Comment by ashishghogre** [comment]
Upgraded Gradle version to 6.0.1 and Java version to 11.
Could not update Java version to 13 as Kotlin doesn't yet support it.
![Screenshot 2019-11-23 at 3 33 46 PM](https://user-images.githubusercontent.com/14134404/69477103-231f4300-0e08-11ea-9ffd-a700b7f78011.png)
